services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379/0
      - API_BASE_URL=https://fakerapi.it/api/v2

  celery_worker:
    build: .
    command: celery -A app.core.celery_app worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379/0
      - API_BASE_URL=https://fakerapi.it/api/v2

  celery_beat:
    build: .
    command: celery -A app.core.celery_app beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - REDIS_URL=redis://redis:6379/0
      - API_BASE_URL=https://fakerapi.it/api/v2

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data:
